name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDD-HH
          utcOffset: "+08:00"
      - name: Use current time
        env:
          TIME: "${{ steps.current-time.outputs.ISOTime }}"
        run: echo $TIME 
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: README.md
          name: test
          tag_name: test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
