name: Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set current date as env variable
        run: echo "NOW::$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: README.md
          name: test
          tag_name: test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
