name: Check release
on:
  pull_request:
    branches: [ main ]

jobs:
 check-files:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v1
    - name: test files
      run: | 
        if [ ! -f models/modelcard.md ]; then
        echo "File not found!"  
        fi
        exit 1

   
